-- ============================================================
-- Real Restaurant Seed Data — Kigali
-- Generated from Restaurant_Prices spreadsheet (18 restaurants)
-- Run after 001_initial.sql
-- ============================================================

-- ─── MERCHANTS ───────────────────────────────────────────────

insert into merchants (name, slug, description, category, city, delivery_fee, delivery_time_min, delivery_time_max, is_open, is_active, rating) values
('Lolo Pits Meats Shop',    'lolo-pits',        'Fresh cuts of chicken, beef, fish and sausages. Quality raw meats delivered.',         'Butcher & Fresh Meat',       'Kigali', 1000, 25, 45, true, true, 4.5),
('Kigali Special Pilau',    'kigali-pilau',     'Pilau rice, broasted chicken, burgers and pizzas. Kigali comfort food done right.',     'Fast Food & Pilau',          'Kigali', 1000, 20, 40, true, true, 4.6),
('Palm Pizza Kitchen',      'palm-pizza',       'Stone-baked pizzas, burgers and fresh sides. 15+ pizza varieties.',                     'Pizza',                      'Kigali', 1000, 25, 45, true, true, 4.4),
('Kings Fresh Shawarma',    'kings-shawarma',   'Shawarma, tacos, quesadillas, gourmet burgers and milkshakes.',                         'Shawarma & Burgers',         'Kigali', 1000, 20, 40, true, true, 4.7),
('Sub Point Restaurant',    'sub-point',        'Pizzas in every variety. Medium and large, classic to gourmet.',                        'Pizza',                      'Kigali', 1000, 30, 50, true, true, 4.3),
('Hot Pot Pizzeria',        'hot-pot-pizzeria', 'Pizzas, shawarma, hot pots, burgers and hot drinks menu.',                              'Pizza & Hot Pot',            'Kigali', 1000, 25, 45, true, true, 4.5),
('Karame',                  'karame',           'Omelets, quesadillas, loaded fries, wraps, curries and grilled chicken.',               'Cafe & Grills',              'Kigali', 1000, 20, 35, true, true, 4.8),
('Riders Lounge',           'riders-lounge',    'Full restaurant with grills, salads, wraps, brochettes and premium sides.',             'Restaurant & Grills',        'Kigali', 1000, 30, 50, true, true, 4.6),
('The Arnauld Pizza',       'arnauld-pizza',    'Chicken meals, burgers and 15+ pizzas. Great value combo deals.',                       'Chicken & Pizza',            'Kigali', 1000, 25, 40, true, true, 4.4),
('Paka',                    'paka',             'East African street food — rolex, chapati, pilau, kebabs and fresh juices.',             'East African & Street Food', 'Kigali', 1000, 20, 35, true, true, 4.7),
('Da Vinci House',          'da-vinci',         'Shawarma, pilau, fajitas — every sandwich comes with energy drink and chips.',          'Middle Eastern & Fast Food', 'Kigali', 1000, 25, 45, true, true, 4.5),
('Now Now Rolex',           'now-now-rolex',    'Creative rolexes and wraps, Tex Mex, nachos, fresh juices, coffee and cocktails.',      'Rolex & Cafe',               'Kigali', 1000, 20, 35, true, true, 4.9),
('Sharons Zone Giporoso',   'sharons-zone',     'Burgers, chicken, salads, smoothies, shakes and Rwandan breakfast.',                    'Burgers & Breakfast',        'Kigali', 1000, 20, 40, true, true, 4.5),
('Goodlife Store',          'goodlife-store',   'Groceries, food supplements and pantry essentials delivered.',                          'Grocery & Essentials',       'Kigali', 1000, 30, 50, true, true, 4.3),
('Casamia Late Night',      'casamia',          'Authentic Italian — handmade pasta, risotto, calzone and fine pizzas.',                 'Italian',                    'Kigali', 1000, 35, 55, true, true, 4.8),
('Inganzo',                 'inganzo',          'Fine dining — breakfast, soups, steaks, T-bone, chicken cordon bleu.',                  'Fine Dining',                'Kigali', 1000, 30, 50, true, true, 4.9),
('Pad Thai',                'pad-thai',         'Authentic Thai — stir fries, curries, pad thai noodles and tom yum soups.',             'Thai & Asian',               'Kigali', 1000, 25, 45, true, true, 4.7),
('Japanda',                 'japanda',          'Japanese ramen, donburi rice bowls, yakitori skewers and sake.',                        'Japanese',                   'Kigali', 1000, 30, 50, true, true, 4.8);

-- Helper function to get merchant id by slug
create or replace function mid(slug_val text) returns uuid language sql as $$
  select id from merchants where slug = slug_val limit 1;
$$;

-- ─── LOLO PITS MEATS SHOP ────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('lolo-pits'), 'Chicken Breast',                   'Fresh raw chicken breast',                       6100),
(mid('lolo-pits'), 'Chicken Leg with Thigh',           'Fresh chicken leg and thigh portion',            9600),
(mid('lolo-pits'), 'Chicken Wings',                    'Fresh raw chicken wings',                        9600),
(mid('lolo-pits'), 'Whole Chicken',                    'Dressed whole raw chicken',                     13500),
(mid('lolo-pits'), 'Beef Shank Cross Cuts (Ijali)',    'Bone-in beef shank slices',                      4100),
(mid('lolo-pits'), 'Mix Cross Cuts (Imvange)',         'Mixed beef cross cuts',                          4100),
(mid('lolo-pits'), 'Beef Ribs (Imbavu)',               'Bone-in beef ribs',                              4100),
(mid('lolo-pits'), 'Beef Brisket',                     'Beef brisket slow cooking cut (Urushyi)',        4100),
(mid('lolo-pits'), 'Beef Sirloin Cross Cuts (Kotereti)','Sirloin cross cut steaks',                     4100),
(mid('lolo-pits'), 'Thomson Fish',                     'Fresh small lake fish',                          4500),
(mid('lolo-pits'), 'Medium Tilapia',                   'Fresh medium-sized tilapia',                     7100),
(mid('lolo-pits'), 'Tilapia Fish Fillet',              'Boneless tilapia fillet',                       11300),
(mid('lolo-pits'), 'Farmers Choice Pork Frankfurter',  'Premium pork frankfurter sausages',             12000),
(mid('lolo-pits'), 'Everyday Frankfurter',             'Everyday frank sausages',                        7500);

-- ─── KIGALI SPECIAL PILAU ────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('kigali-pilau'), 'Soda',                          'Coke, Fanta, Sprite',                            1500),
(mid('kigali-pilau'), 'Water (Small)',                  'Bottled mineral water 500ml',                    1000),
(mid('kigali-pilau'), 'Water (Large)',                  'Bottled mineral water 1.5L',                     1500),
(mid('kigali-pilau'), 'Beef Burger',                    'Beef patty burger',                              5000),
(mid('kigali-pilau'), 'Chicken Burger',                 'Crispy chicken burger',                          6000),
(mid('kigali-pilau'), 'Chicken BBQ Pizza (Small)',      'BBQ chicken pizza, small',                       5000),
(mid('kigali-pilau'), 'Chicken BBQ Pizza (Medium)',     'BBQ chicken pizza, medium',                      8000),
(mid('kigali-pilau'), 'Chicken BBQ Pizza (Large)',      'BBQ chicken pizza, large',                      10000),
(mid('kigali-pilau'), 'Meat Lovers Pizza (Small)',      'Meat lovers pizza, small',                       5000),
(mid('kigali-pilau'), 'Meat Lovers Pizza (Medium)',     'Meat lovers pizza, medium',                      8000),
(mid('kigali-pilau'), 'Pepperoni Pizza (Medium)',       'Pepperoni pizza, medium',                        8000),
(mid('kigali-pilau'), 'Whole Chicken',                  'Full fried whole chicken',                      15000),
(mid('kigali-pilau'), '1 Piece Chicken with Chips',     '1 piece chicken with fries',                     7000),
(mid('kigali-pilau'), '2 Piece Chicken with Chips',     '2 pieces chicken with fries',                   11000),
(mid('kigali-pilau'), '3 Piece Chicken with Chips',     '3 pieces chicken with fries',                   15000),
(mid('kigali-pilau'), 'Full Chicken with Chips',        'Full chicken with fries',                       22000),
(mid('kigali-pilau'), 'Beef Pilau with Chips',          'Beef pilau rice with chips',                    14000);

-- ─── PALM PIZZA KITCHEN ──────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('palm-pizza'), 'BBQ Chicken Pizza (Small)',        'BBQ chicken and tomato pizza, small',            6000),
(mid('palm-pizza'), 'BBQ Chicken Pizza (Medium)',       'BBQ chicken and tomato pizza, medium',           9000),
(mid('palm-pizza'), 'Pepperoni Pizza (Small)',          'Classic pepperoni, small',                       6000),
(mid('palm-pizza'), 'Pepperoni Pizza (Medium)',         'Classic pepperoni, medium',                      9000),
(mid('palm-pizza'), 'Margarita Pizza (Small)',          'Tomato and mozzarella, small',                   6000),
(mid('palm-pizza'), 'Margarita Pizza (Medium)',         'Tomato and mozzarella, medium',                  9000),
(mid('palm-pizza'), 'Beef Special Pizza (Small)',       'Beef special pizza, small',                      6000),
(mid('palm-pizza'), 'Beef Special Pizza (Medium)',      'Beef special pizza, medium',                     9000),
(mid('palm-pizza'), 'Hawaiian Pizza (Small)',           'Ham and pineapple, small',                       6000),
(mid('palm-pizza'), 'Vegetarian Pizza (Small)',         'Vegetarian pizza, small',                        6000),
(mid('palm-pizza'), 'Meat Lovers (Small)',              'Meat lovers pizza, small',                       6000),
(mid('palm-pizza'), 'Chicken Supreme (Medium)',         'Chicken supreme + one free topping, medium',    11000),
(mid('palm-pizza'), 'Harvard Pizza (Medium)',           'Harvard special + one free topping, medium',    11000),
(mid('palm-pizza'), 'Beef Burger',                      'Classic beef patty burger',                      5500),
(mid('palm-pizza'), 'Cheese Burger',                    'Cheese burger',                                  5000),
(mid('palm-pizza'), 'Chicken Burger',                   'Crispy chicken burger',                          6000),
(mid('palm-pizza'), 'Plain Chips',                      'Crispy plain fries',                             2000),
(mid('palm-pizza'), 'Soda (500ml)',                     'Coke, Sprite, Orange, Citron',                   1500),
(mid('palm-pizza'), 'Soda (1.5L)',                      'Large soda bottle',                              3000);

-- ─── KINGS FRESH SHAWARMA ────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('kings-shawarma'), 'Chicken Shawarma',             'Grilled chicken shawarma wrap',                  7000),
(mid('kings-shawarma'), 'Beef Shawarma',                'Beef shawarma wrap',                             7500),
(mid('kings-shawarma'), 'King Mixed Shawarma',          'Mixed chicken and beef shawarma',                8000),
(mid('kings-shawarma'), 'Lamb Shawarma',                'Lamb shawarma wrap',                             7000),
(mid('kings-shawarma'), 'Mushroom Shawarma',            'Mushroom shawarma, vegetarian',                  4000),
(mid('kings-shawarma'), 'Vegetarian Shawarma',          'Vegetarian shawarma wrap',                       4000),
(mid('kings-shawarma'), 'Grilled Chicken Taco',         'Grilled chicken taco',                           9000),
(mid('kings-shawarma'), 'Grilled Steak Taco',           'Grilled beef steak taco',                        8500),
(mid('kings-shawarma'), 'Steak, Bacon & Cheese Taco',   'Premium loaded taco',                           10000),
(mid('kings-shawarma'), 'Vegan Taco',                   'Vegetarian taco',                                6000),
(mid('kings-shawarma'), 'Slow Cooked Beef Taco',        'Slow cooked beef taco',                          8000),
(mid('kings-shawarma'), 'Chicken Quesadilla',           'Grilled chicken quesadilla',                     6000),
(mid('kings-shawarma'), 'Vegetable Quesadilla',         'Vegetable quesadilla',                           4500),
(mid('kings-shawarma'), 'Beef Burger',                  'Classic beef burger',                            6500),
(mid('kings-shawarma'), 'Chicken Burger',               'Crispy chicken burger',                          5000),
(mid('kings-shawarma'), 'Double Burger',                'Double patty burger',                            7500),
(mid('kings-shawarma'), 'Bacon Cheese Burger',          'Bacon and cheese burger',                        8000),
(mid('kings-shawarma'), 'Smashed Burger',               'Smash-style beef burger',                        7000),
(mid('kings-shawarma'), 'Avocado Burger',               'Burger with avocado',                            6500),
(mid('kings-shawarma'), 'The Ultimate Burger',          'Kings signature loaded burger',                  8500),
(mid('kings-shawarma'), 'Chips',                        'Crispy fries',                                   3000),
(mid('kings-shawarma'), 'Vanilla Milkshake',            'Creamy vanilla milkshake',                       4000),
(mid('kings-shawarma'), 'Chocolate Milkshake',          'Creamy chocolate milkshake',                     4000),
(mid('kings-shawarma'), 'Strawberry Milkshake',         'Fresh strawberry milkshake',                     4000),
(mid('kings-shawarma'), 'Soda',                         'Coke, Sprite, Orange, Pineapple',                2000);

-- ─── SUB POINT RESTAURANT ────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('sub-point'), 'Margharita (Medium)',               'Classic margharita pizza, medium',               9000),
(mid('sub-point'), 'Margharita (Large)',                'Classic margharita pizza, large',               11500),
(mid('sub-point'), 'Pepperoni (Medium)',                'Pepperoni pizza, medium',                       10000),
(mid('sub-point'), 'Pepperoni (Large)',                 'Pepperoni pizza, large',                        12500),
(mid('sub-point'), 'BBQ Steak (Medium)',                'BBQ steak pizza, medium',                       10000),
(mid('sub-point'), 'Chicken BBQ (Medium)',              'Chicken BBQ pizza, medium',                     10500),
(mid('sub-point'), 'Chicken BBQ (Large)',               'Chicken BBQ pizza, large',                      12500),
(mid('sub-point'), 'Hawaiian (Medium)',                 'Hawaiian pizza, medium',                        10000),
(mid('sub-point'), 'Hawaiian (Large)',                  'Hawaiian pizza, large',                         12500),
(mid('sub-point'), 'Meat Deluxe (Medium)',              'Loaded meat pizza, medium',                     10500),
(mid('sub-point'), 'Meat Deluxe (Large)',               'Loaded meat pizza, large',                      13000),
(mid('sub-point'), 'Chicken Mushroom (Medium)',         'Chicken mushroom pizza, medium',                10000),
(mid('sub-point'), 'Four Seasons (Medium)',             'Four seasons pizza, medium',                    10500),
(mid('sub-point'), 'Fully Loaded (Medium)',             'Fully loaded toppings pizza, medium',           10500),
(mid('sub-point'), 'Veggy Feast Spicy (Medium)',        'Spicy vegetarian pizza, medium',                10000),
(mid('sub-point'), 'Mediterranean (Medium)',            'Mediterranean style pizza, medium',             10000),
(mid('sub-point'), 'Tuna Pizza (Medium)',               'Tuna pizza, medium',                            10500),
(mid('sub-point'), 'Chicken Tikka (Medium)',            'Chicken tikka pizza, medium',                   10500),
(mid('sub-point'), 'Extra Cheese',                      'Add extra cheese to any pizza',                  1000),
(mid('sub-point'), 'Extra Mushroom',                    'Add extra mushroom to any pizza',                1000);

-- ─── HOT POT PIZZERIA ────────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('hot-pot-pizzeria'), 'Margaritha Pizza',           'Classic margherita pizza',                       9500),
(mid('hot-pot-pizzeria'), 'BBQ Chicken Pizza',          'BBQ chicken pizza',                             11000),
(mid('hot-pot-pizzeria'), 'Four Season Pizza',          'Four season pizza',                             11000),
(mid('hot-pot-pizzeria'), 'Bolognese Pizza',            'Bolognese beef pizza',                          10000),
(mid('hot-pot-pizzeria'), 'Hawaiian Pizza',             'Ham and pineapple pizza',                       12000),
(mid('hot-pot-pizzeria'), 'Pepperoni Pizza',            'Classic pepperoni pizza',                       12000),
(mid('hot-pot-pizzeria'), 'Mixte Pizza',                'Mixed toppings pizza',                          13000),
(mid('hot-pot-pizzeria'), 'Hotpot Special Pizza',       'Hotpot signature pizza',                        14000),
(mid('hot-pot-pizzeria'), 'Chicken Burger',             'Crispy chicken burger',                          6000),
(mid('hot-pot-pizzeria'), 'Beef Burger',                'Classic beef burger',                            6000),
(mid('hot-pot-pizzeria'), 'Plain Vegetables Burger',    'Vegetarian burger',                              4500),
(mid('hot-pot-pizzeria'), 'Chicken Shawarma Wrap',      'Grilled chicken shawarma wrap',                  7000),
(mid('hot-pot-pizzeria'), 'Beef Shawarma Wrap',         'Beef shawarma wrap',                             6500),
(mid('hot-pot-pizzeria'), 'Chicken & Spaghetti Hot Pot','Chicken with spaghetti in hot pot',              6500),
(mid('hot-pot-pizzeria'), 'Chicken & Rice Pot',         'Chicken and rice hot pot',                       6500),
(mid('hot-pot-pizzeria'), 'Special Omelette',           'Special fried omelette',                         4500),
(mid('hot-pot-pizzeria'), 'Whole Chicken Biryani',      'Full chicken biryani for sharing',              25000),
(mid('hot-pot-pizzeria'), 'Chicken Leg',                'Grilled chicken leg',                            6000),
(mid('hot-pot-pizzeria'), 'Chicken Wings',              'Crispy chicken wings',                           5000),
(mid('hot-pot-pizzeria'), 'Plain Chips',                'Plain fries',                                    2500),
(mid('hot-pot-pizzeria'), 'Fried Rice',                 'Egg fried rice',                                 3000),
(mid('hot-pot-pizzeria'), 'Black Coffee',               'Rwandan black coffee',                           2000),
(mid('hot-pot-pizzeria'), 'Hot Chocolate',              'Rich hot chocolate',                             3000),
(mid('hot-pot-pizzeria'), 'African Coffee',             'Spiced African coffee',                          3000),
(mid('hot-pot-pizzeria'), 'Soda',                       'Coke, Sprite, Orange, Citron',                   1500),
(mid('hot-pot-pizzeria'), 'Mineral Water',              'Bottled water',                                  1000);

-- ─── KARAME ──────────────────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('karame'), 'Classic Omelet',                       'Classic two-egg omelette',                       5000),
(mid('karame'), 'Beef Omelet',                          'Omelette with seasoned beef',                    6000),
(mid('karame'), 'Sausage Omelet',                       'Omelette with sausage',                          6500),
(mid('karame'), 'Meatlovers Omelet',                    'Loaded meatlovers omelette',                     7000),
(mid('karame'), 'Chicken Omelet',                       'Omelette with grilled chicken',                  7000),
(mid('karame'), 'Chicken Quesadilla',                   'Grilled chicken quesadilla',                     9000),
(mid('karame'), 'Beef Quesadilla',                      'Beef quesadilla',                                8000),
(mid('karame'), 'Sausage Quesadilla',                   'Sausage quesadilla',                             9000),
(mid('karame'), 'Meatlovers Quesadilla',                'Loaded meatlovers quesadilla',                   9500),
(mid('karame'), 'Vegetarian Quesadilla',                'Vegetable quesadilla',                           7500),
(mid('karame'), 'Beef Burger',                          'Classic beef burger',                            7000),
(mid('karame'), 'Grilled Chicken Burger',               'Grilled chicken burger',                         9000),
(mid('karame'), 'Beef Cheese Burger',                   'Beef and cheese burger',                         8000),
(mid('karame'), 'Double Beef Burger',                   'Double patty beef burger',                      10000),
(mid('karame'), 'Karame Beef Rolex',                    'Signature beef rolex wrap',                      6000),
(mid('karame'), 'Grilled Chicken Rolex',                'Grilled chicken rolex wrap',                     7000),
(mid('karame'), 'Sausage & Beef Rolex',                 'Sausage and beef rolex',                         7000),
(mid('karame'), 'Meatlovers Rolex',                     'Fully loaded meatlovers rolex',                  8000),
(mid('karame'), 'Karame Veggie Rolex',                  'Vegetarian rolex wrap',                          5000),
(mid('karame'), 'Beef Loaded Fries',                    'Fries loaded with beef',                         7000),
(mid('karame'), 'Chicken Loaded Fries',                 'Fries loaded with chicken',                      8000),
(mid('karame'), 'Sausage Loaded Fries',                 'Fries loaded with sausage',                      8000),
(mid('karame'), 'Meatlovers Loaded Fries',              'Ultimate loaded fries',                          9000),
(mid('karame'), 'Avocado Chips',                        'Avocado with chips',                             5000),
(mid('karame'), 'Chips Salad',                          'Chips with fresh salad',                         4000),
(mid('karame'), 'Spicy Curry Chicken',                  'Spicy chicken curry with rice',                  9000),
(mid('karame'), 'Basil Chicken Rice',                   'Thai basil chicken with rice',                   9000),
(mid('karame'), 'Grilled Chicken Leg',                  'Grilled chicken leg, marinated',                 8500),
(mid('karame'), 'Grilled Chicken Breast',               'Grilled chicken breast',                        10000);

-- ─── RIDERS LOUNGE ───────────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('riders-lounge'), 'Wet Fry Beef',                  'Wet fry beef. Choose side: fries, mash, fried rice, wedges, steamed rice or ugali', 18000),
(mid('riders-lounge'), 'Wet Fry Chicken',               'Wet fry chicken with choice of side',           18000),
(mid('riders-lounge'), 'Wet Fry Pork',                  'Wet fry pork with choice of side',              18000),
(mid('riders-lounge'), 'Tilapia Fish Fillet',           'Tilapia fillet with choice of side',            16000),
(mid('riders-lounge'), 'Spaghetti Bolognaise',          'Bolognese spaghetti',                           14000),
(mid('riders-lounge'), 'Spaghetti Carbonara',           'Creamy carbonara spaghetti',                    14000),
(mid('riders-lounge'), 'Stir Fried Beef',               'Stir fried beef with choice of side',           16000),
(mid('riders-lounge'), 'Stir Fried Chicken',            'Stir fried chicken with choice of side',        16000),
(mid('riders-lounge'), 'Pork Ribs',                     'BBQ pork ribs with choice of side',             18000),
(mid('riders-lounge'), 'Half Roasted Chicken',          'Roasted half chicken with choice of side',      17000),
(mid('riders-lounge'), 'Grilled Chicken Breast',        'Grilled chicken breast with choice of side',    15000),
(mid('riders-lounge'), 'Pork Chops',                    'Grilled pork chops with choice of side',        21000),
(mid('riders-lounge'), 'Classical Beef Burger',         'Classic beef burger',                           15000),
(mid('riders-lounge'), 'BBQ Burger',                    'BBQ beef burger',                               14000),
(mid('riders-lounge'), 'Riders Special Burger',         'Signature riders burger',                       17000),
(mid('riders-lounge'), 'Vegetarian Burger',             'Vegetarian burger',                              9500),
(mid('riders-lounge'), 'Chicken Wrap',                  'Grilled chicken wrap',                          14000),
(mid('riders-lounge'), 'Beef Wrap',                     'Beef wrap',                                     14000),
(mid('riders-lounge'), 'Club Sandwich',                 'Classic club sandwich',                         16000),
(mid('riders-lounge'), 'Beef Sandwich',                 'Beef sandwich',                                 14000),
(mid('riders-lounge'), 'Goat Brochettes (3pcs)',        'Three goat brochettes',                         14000),
(mid('riders-lounge'), 'Beef Brochettes (3pcs)',        'Three beef brochettes',                         14000),
(mid('riders-lounge'), 'Pork Brochettes (3pcs)',        'Three pork brochettes',                         14000),
(mid('riders-lounge'), 'Chicken Wings',                 'Crispy chicken wings',                          14000),
(mid('riders-lounge'), 'Chicken Lollipops',             'Chicken lollipop bites',                        14000),
(mid('riders-lounge'), 'Green Salad',                   'Fresh garden green salad',                       9000),
(mid('riders-lounge'), 'Classical Caesar Salad',        'Caesar salad with dressing',                    12000),
(mid('riders-lounge'), 'Avocado & Mango Salad',         'Avocado and mango salad',                       10000),
(mid('riders-lounge'), 'Riders Special Salad',         'Chicken and mango salad',                        11000),
(mid('riders-lounge'), 'French Fries',                  'Crispy french fries',                            6000),
(mid('riders-lounge'), 'Plantain Chips',                'Fried plantain chips',                           6000),
(mid('riders-lounge'), 'Potato Wedges',                 'Seasoned potato wedges',                         5000),
(mid('riders-lounge'), 'Steamed Rice',                  'Plain steamed rice',                             5000),
(mid('riders-lounge'), 'Creamy Mash',                   'Creamy mashed potatoes',                         4000),
(mid('riders-lounge'), 'Ugali',                         'East African maize ugali',                       3500);

-- ─── THE ARNAULD PIZZA ───────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('arnauld-pizza'), '1 Piece Chicken with Chips',    '1 piece fried chicken with chips',               4000),
(mid('arnauld-pizza'), '2 Pieces Chicken + Soda',       '2 pieces chicken, chips and soda',               7000),
(mid('arnauld-pizza'), '3 Pieces Chicken + Soda',       '3 pieces chicken, chips, coleslaw and soda',    10000),
(mid('arnauld-pizza'), '5 Pieces Chicken + Soda',       '5 pieces chicken, chips and soda',              12500),
(mid('arnauld-pizza'), '9 Pieces Chicken Family',       '9 pieces chicken, 2 chips, 2 sodas',            21000),
(mid('arnauld-pizza'), 'Grilled Chicken Burger',         'Grilled chicken burger',                         6000),
(mid('arnauld-pizza'), 'Mr Chicken Club',                'Chicken club burger',                            6000),
(mid('arnauld-pizza'), 'Beef Burger & Chips',            'Beef burger with chips',                         6000),
(mid('arnauld-pizza'), 'Cheese Burger & Chips',          'Cheese burger with chips',                       6500),
(mid('arnauld-pizza'), 'Double Cheese Burger',           'Double cheese burger with chips',                8500),
(mid('arnauld-pizza'), 'Double Beef Burger & Chips',     'Double beef burger with chips',                  8000),
(mid('arnauld-pizza'), 'Margarita Pizza',                'Classic margarita pizza',                        9000),
(mid('arnauld-pizza'), 'Hawaiian Pizza',                 'Ham and pineapple pizza',                        9500),
(mid('arnauld-pizza'), 'Americano Pizza',                'Arnauld Americano pizza',                       10000),
(mid('arnauld-pizza'), 'Meat Lovers Pizza',              'Loaded meat pizza',                             10000),
(mid('arnauld-pizza'), 'Pepperoni Pizza',                'Classic pepperoni pizza',                       10000),
(mid('arnauld-pizza'), 'BBQ Steak Pizza',                'BBQ steak pizza',                               10000),
(mid('arnauld-pizza'), 'Chicken Pizza',                  'Chicken pizza',                                 10000),
(mid('arnauld-pizza'), 'Four Season Pizza',              'Four season pizza',                             10000),
(mid('arnauld-pizza'), 'Kila Kitu Pizza',                'Full toppings pizza',                           11500),
(mid('arnauld-pizza'), 'Soda',                           'Coke, Fanta, Sprite 500ml',                      1500),
(mid('arnauld-pizza'), 'Water',                          'Mineral water',                                  1000);

-- ─── PAKA ────────────────────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('paka'), 'Plain Chicken',                          'Plain fried chicken',                            4000),
(mid('paka'), 'Chips & Chicken',                        'Chips and fried chicken piece',                  6000),
(mid('paka'), 'Pilao Chips & Chicken',                  'Pilao-spiced chips with chicken',                6000),
(mid('paka'), 'Pilao Chicken',                          'Pilao spiced chicken',                           6000),
(mid('paka'), 'Rice & Liver',                           'Rice with beef liver',                           5000),
(mid('paka'), 'White Rice or Pilao',                    'Choice of plain white rice or pilao',            4000),
(mid('paka'), 'Plain Chips',                            'Plain fries',                                    3000),
(mid('paka'), 'Beef Stew',                              'Rwandan beef stew',                              3500),
(mid('paka'), 'Paka Chapati',                           'Fresh handmade chapati',                         1000),
(mid('paka'), 'Vegetable Rolex',                        'Vegetable rolex chapati wrap',                   2500),
(mid('paka'), 'Beef Rolex',                             'Beef rolex chapati wrap',                        3500),
(mid('paka'), 'Chicken Rolex',                          'Chicken rolex chapati wrap',                     4000),
(mid('paka'), 'Beef Burger with Fries',                 'Beef burger and fries',                          6500),
(mid('paka'), 'Chicken Burger with Fries',              'Chicken burger and fries',                       7000),
(mid('paka'), 'Spaghetti Bolognaise',                   'Bolognese spaghetti',                            5000),
(mid('paka'), 'Beef Samosas',                           'Fresh beef samosas',                             1000),
(mid('paka'), 'Kebab',                                  'Grilled beef kebab',                             2000),
(mid('paka'), 'Meatballs',                              'Spiced meatballs',                               1000),
(mid('paka'), 'Kikomando',                              'Chapati with beans — East African staple',       3000),
(mid('paka'), 'Paka Platter (Lasuniya)',                'Sharing platter for groups',                    30000),
(mid('paka'), 'Passion Juice',                          'Fresh passion fruit juice',                      3000),
(mid('paka'), 'Mango Juice',                            'Fresh mango juice',                              3500),
(mid('paka'), 'Cocktail Juice',                         'Mixed fruit cocktail juice',                     3500),
(mid('paka'), 'Soda (500ml)',                           'Coke, Fanta, Pepsi',                             1500),
(mid('paka'), 'Water',                                  'Mineral water',                                  1000);

-- ─── DA VINCI HOUSE ──────────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('da-vinci'), 'Chicken Shawarma',                   'Chicken shawarma with energy drink and chips',   8000),
(mid('da-vinci'), 'Chicken Fajita',                     'Chicken fajita with energy drink and chips',     8000),
(mid('da-vinci'), 'Beef Fajita',                        'Beef fajita with energy drink and chips',        8000),
(mid('da-vinci'), 'Beef Shawarma',                      'Beef shawarma with energy drink and chips',      8000),
(mid('da-vinci'), 'Beef Kojita',                        'Beef kojita sandwich with energy drink and chips', 8000),
(mid('da-vinci'), 'Philadelphia Sandwich',              'Philadelphia with energy drink and chips',       8000),
(mid('da-vinci'), 'Vegetarian Falafel',                 'Falafel wrap with energy drink and chips',       7000),
(mid('da-vinci'), 'Vegetarian Foul Medames',            'Foul medames with energy drink and chips',       5000),
(mid('da-vinci'), 'Whole Chicken',                      'Full chicken with chips, energy drink and salad', 22000),
(mid('da-vinci'), 'Half Chicken',                       'Half chicken with chips, energy drink and salad', 12000),
(mid('da-vinci'), 'Whole Fish',                         'Whole fish with chips, energy drink and salad',  15000),
(mid('da-vinci'), 'Beef Pilau',                         'Beef pilau with energy drink and chips',         10000),
(mid('da-vinci'), 'Chicken Pilau',                      'Chicken pilau with energy drink and chips',      10000),
(mid('da-vinci'), 'Mix Pilau',                          'Mixed pilau with chips',                         12000),
(mid('da-vinci'), 'Fattah Beef Shawarma',               'Fattah-style beef shawarma with energy drink',   10000),
(mid('da-vinci'), 'Fattah Chicken Shawarma',            'Fattah-style chicken shawarma with energy drink', 10000),
(mid('da-vinci'), 'Beef Burger',                        'Beef burger with energy drink and chips',         7000),
(mid('da-vinci'), 'Cheese Burger',                      'Cheese burger with energy drink and chips',       8000),
(mid('da-vinci'), 'Chicken Burger',                     'Chicken burger with energy drink and chips',      7000),
(mid('da-vinci'), 'Green Salad',                        'Fresh green salad',                               3000);

-- ─── NOW NOW ROLEX ───────────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('now-now-rolex'), 'The Rwandan Beef Rolex',        'Classic Rwandan beef rolex',                     4500),
(mid('now-now-rolex'), 'The Ugandan Rolex',             'Classic Ugandan-style rolex',                    4500),
(mid('now-now-rolex'), 'The Rwandan Chicken Rolex',     'Rwandan chicken rolex wrap',                     7000),
(mid('now-now-rolex'), 'The Korean Rolex',              'Korean-style rolex wrap',                        8000),
(mid('now-now-rolex'), 'The Goat Cheese Rolex',         'Goat cheese rolex wrap',                         7000),
(mid('now-now-rolex'), 'BBQ Chicken Rolex',             'BBQ chicken rolex wrap',                         7500),
(mid('now-now-rolex'), 'Feta and Avocado Wrap',         'Feta and avocado wrap',                          7500),
(mid('now-now-rolex'), 'The Mexican Beef Rolex',        'Mexican-spiced beef rolex',                      7000),
(mid('now-now-rolex'), 'The Mexican Chicken Rolex',     'Mexican chicken rolex',                          8000),
(mid('now-now-rolex'), 'The Bacon & Cheddar Rolex',     'Bacon and cheddar rolex',                        8000),
(mid('now-now-rolex'), 'The Italian Rolex',             'Italian-style rolex',                            7000),
(mid('now-now-rolex'), 'The Greek Rolex',               'Greek-style rolex',                              7000),
(mid('now-now-rolex'), 'Nachos Plain',                  'Plain nachos with dip',                          6000),
(mid('now-now-rolex'), 'Nachos Spiced Beef',            'Nachos with spiced beef',                        8000),
(mid('now-now-rolex'), 'Nachos Fajita Chicken',         'Nachos with fajita chicken',                    10000),
(mid('now-now-rolex'), 'Chilli Beef Cheese Fries',      'Chilli beef cheese loaded fries',                8000),
(mid('now-now-rolex'), 'Chili Fries Chicken',           'Fajita chicken chili fries',                    10000),
(mid('now-now-rolex'), 'Chips & Dip',                   'Chips with dipping sauce',                       3500),
(mid('now-now-rolex'), 'Fries',                         'Plain fries',                                    3000),
(mid('now-now-rolex'), 'Passion Fruit Juice',           'Fresh passion fruit juice',                      4000),
(mid('now-now-rolex'), 'Pineapple Juice',               'Fresh pineapple juice',                          5000),
(mid('now-now-rolex'), 'Watermelon Juice',              'Fresh watermelon juice',                         3000),
(mid('now-now-rolex'), 'Tropical Cleanse Juice',        'Tropical cleansing juice blend',                 5000),
(mid('now-now-rolex'), 'Rwandan Tea',                   'Fresh Rwandan tea',                              2000),
(mid('now-now-rolex'), 'African Tea',                   'Spiced Rwandan African tea',                     5000),
(mid('now-now-rolex'), 'Hot Chocolate',                 'Rich hot chocolate',                             4000),
(mid('now-now-rolex'), 'Cold Brew Coffee',              'Cold brew Rwandan coffee',                       4000),
(mid('now-now-rolex'), 'Rwandan Black Coffee',          'Single-origin Rwandan filter coffee',            1500),
(mid('now-now-rolex'), 'Passion Whisky Sour',           'Fresh passion fruit whisky sour cocktail',      10000);

-- ─── SHARONS ZONE GIPOROSO ───────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('sharons-zone'), 'Beef Burger',                    'Classic beef burger',                            4800),
(mid('sharons-zone'), 'Cheese Burger',                  'Cheese burger',                                  5500),
(mid('sharons-zone'), 'Double Burger',                  'Double patty burger',                            6000),
(mid('sharons-zone'), 'Chicken Burger',                 'Crispy chicken burger',                          6500),
(mid('sharons-zone'), 'Grilled Chicken Burger',         'Grilled chicken burger',                         5500),
(mid('sharons-zone'), 'Chicken Barbecue Burger',        'BBQ chicken burger',                             6000),
(mid('sharons-zone'), 'Chicken Leg',                    'Grilled chicken leg',                            5000),
(mid('sharons-zone'), 'Chicken Breast',                 'Grilled chicken breast',                         5800),
(mid('sharons-zone'), 'Chicken Curry',                  'Rwandan-style chicken curry',                    5000),
(mid('sharons-zone'), 'Whole Chicken',                  'Whole fried or grilled chicken',                18000),
(mid('sharons-zone'), 'Home Style Chicken',             'Home-style cooked chicken',                      6500),
(mid('sharons-zone'), 'Home Style Beef',                'Home-style beef',                                6000),
(mid('sharons-zone'), 'Special Omelette',               'Special omelette breakfast',                     3500),
(mid('sharons-zone'), 'Beef Pilau Rice',                'Beef pilau with fresh sides',                    8000),
(mid('sharons-zone'), 'Chicken Fried Rice',             'Egg fried rice with chicken',                    3500),
(mid('sharons-zone'), 'Regular Chips',                  'Plain fries',                                    2000),
(mid('sharons-zone'), 'Sharon Cheesy Fries',            'Signature cheesy fries',                         3000),
(mid('sharons-zone'), 'Curry Fries',                    'Curry-spiced fries',                             3000),
(mid('sharons-zone'), 'Avocado Salad',                  'Fresh avocado salad',                            3800),
(mid('sharons-zone'), 'Chicken Salad',                  'Grilled chicken salad',                          4800),
(mid('sharons-zone'), 'Chicken Crunchy Salad',          'Crunchy chicken salad',                          6000),
(mid('sharons-zone'), 'Vanilla Shake',                  'Vanilla milkshake',                              3000),
(mid('sharons-zone'), 'Chocolate Shake',                'Chocolate milkshake',                            3000),
(mid('sharons-zone'), 'Strawberry Shake',               'Strawberry milkshake',                           3000),
(mid('sharons-zone'), 'Mango Smoothie',                 'Fresh mango smoothie',                           3000),
(mid('sharons-zone'), 'Mixed Juice',                    'Fresh mixed fruit juice',                        3000),
(mid('sharons-zone'), 'Passion Juice',                  'Fresh passion fruit juice',                      2500),
(mid('sharons-zone'), 'African Tea',                    'Spiced African tea',                             3000),
(mid('sharons-zone'), 'Soda',                           'Fanta, Coke, Sprite',                            1500);

-- ─── GOODLIFE STORE ──────────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('goodlife-store'), 'Fit Tea 28 Day Slimming',      '28-teabag slimming tea',                        13000),
(mid('goodlife-store'), 'Hemani Slim Tea',               '20-teabag slim tea',                             6500),
(mid('goodlife-store'), 'Zima Chia Seeds',               'Premium chia seeds',                             6500),
(mid('goodlife-store'), 'Nescafe Classic (200g)',        'Nescafe Classic coffee jar',                    12600),
(mid('goodlife-store'), 'Apple Cider Vinegar (946ml)',   'Apple cider vinegar',                           24000),
(mid('goodlife-store'), 'Nut Gold Peanut Butter',        'Creamy peanut butter',                           7600),
(mid('goodlife-store'), 'Jambo Basmati Rice (5kg)',      'Premium basmati rice 5kg',                      16500),
(mid('goodlife-store'), 'Baba Noor Basmati (10kg)',      'Premium basmati 10kg',                          32500),
(mid('goodlife-store'), 'Crystal Vegetable Oil (3L)',    'Vegetable cooking oil 3L',                      15800),
(mid('goodlife-store'), 'Karanga Oil (3L)',              'Groundnut cooking oil 3L',                       8000),
(mid('goodlife-store'), 'Illovo Sugar (1kg)',            'White sugar 1kg',                                1900),
(mid('goodlife-store'), 'Inyange Whole Milk (1L)',       'Fresh whole milk 1L',                            1700),
(mid('goodlife-store'), 'Herman Tomato Ketchup (340g)', 'Tomato ketchup',                                  2000),
(mid('goodlife-store'), 'Indomie Chicken Noodles',       'Instant chicken flavour noodles',                  400),
(mid('goodlife-store'), 'Santa Lucia Spaghetti',         'Spaghetti pasta',                                1300),
(mid('goodlife-store'), 'Maggi Star (156g)',             'Maggi seasoning cubes',                          2100),
(mid('goodlife-store'), 'Roasted Cashew Nuts',           'House of Nuts roasted cashews',                  9500),
(mid('goodlife-store'), 'Dairyland Milk Chocolate',      'Rwandan milk chocolate bar',                     3000),
(mid('goodlife-store'), 'Winnaz Salted Chips',           'Crunchy salted chips',                           2600),
(mid('goodlife-store'), 'Fanta Orange (500ml)',          'Fanta Orange 500ml',                             1000),
(mid('goodlife-store'), 'Wow Natural Spring Water',      'Spring water 500ml',                               400),
(mid('goodlife-store'), 'Circular Mosquito Net (Large)', 'Large circular mosquito net',                   12000);

-- ─── CASAMIA LATE NIGHT ──────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('casamia'), 'Margarita Pizza',                     'Classic Italian margarita pizza',               11500),
(mid('casamia'), 'Prosciutto Pizza',                    'Prosciutto classic pizza',                      13800),
(mid('casamia'), 'Salame Pizza',                        'Salami pizza',                                  13800),
(mid('casamia'), 'Funghi Pizza',                        'Mushroom pizza',                                14300),
(mid('casamia'), 'Regina Pizza',                        'Regina classic pizza',                          14300),
(mid('casamia'), 'Quattro Stagioni',                    'Four seasons signature pizza',                  18900),
(mid('casamia'), 'Diavolo Pizza',                       'Spicy diavolo signature pizza',                 18900),
(mid('casamia'), 'Milano Pizza',                        'Milano signature pizza',                        16000),
(mid('casamia'), 'Gamberetti (Prawn Pizza)',             'Prawn seafood pizza',                           18500),
(mid('casamia'), 'Frutti di Mare',                      'Mixed seafood pizza',                           21000),
(mid('casamia'), 'Quattro Formaggi',                    'Four cheese pizza',                             15000),
(mid('casamia'), 'Pizza Mexicano',                      'Mexican-style signature pizza',                 14500),
(mid('casamia'), 'Siciliana Pizza',                     'Sicilian style pizza',                          15500),
(mid('casamia'), 'Bolognese Pizza',                     'Bolognese meat pizza',                          13200),
(mid('casamia'), 'Fried Pizza Tomato Mozzarella',       'Small fried pizza, tomato and mozzarella',      10000),
(mid('casamia'), 'Fried Pizza Minced Beef',             'Small fried pizza with minced beef',            12500),
(mid('casamia'), 'Gnocchi alla Sorrentina',             'Handmade gnocchi in tomato sauce',              16000),
(mid('casamia'), 'Lasagna Classica',                    'Classic baked lasagna',                         16500),
(mid('casamia'), 'Tagliatelle Al Alfredo',              'Creamy alfredo tagliatelle pasta',              16500),
(mid('casamia'), 'Tagliatelle Al Salmone',              'Salmon tagliatelle pasta',                      17500),
(mid('casamia'), 'Spaghetti Carbonara',                 'Classic carbonara spaghetti',                   15500),
(mid('casamia'), 'Spaghetti Marinara',                  'Seafood marinara spaghetti',                    16000),
(mid('casamia'), 'Spaghetti Al Ragu',                   'Ragu meat spaghetti',                           12500),
(mid('casamia'), 'Penne Alle Verdure',                  'Vegetable penne pasta',                         13500),
(mid('casamia'), 'Risotto Ai Frutti Di Mare',           'Seafood risotto',                               19500),
(mid('casamia'), 'Chicken Wings',                       'Crispy chicken wings starter',                   8500),
(mid('casamia'), 'Meatballs al Pomodoro',               'Italian meatballs in tomato sauce',             13500),
(mid('casamia'), 'Bruschetta al Pomodoro',              'Tomato bruschetta',                              7900),
(mid('casamia'), 'Classica Calzone',                    'Classic folded calzone',                         9500),
(mid('casamia'), 'Regina Calzone',                      'Signature Regina calzone',                      14400),
(mid('casamia'), 'Beef Brochette',                      'Grilled beef brochette',                        17200),
(mid('casamia'), 'Chicken Stroganoff',                  'Creamy chicken stroganoff',                     19500),
(mid('casamia'), 'Zuppa al Pomodoro',                   'Italian tomato soup',                            6300);

-- ─── INGANZO ─────────────────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('inganzo'), 'Simple Breakfast',                    'Bread, omelette, African tea and juice',         6000),
(mid('inganzo'), 'Continental Delight Breakfast',       'Fruits, omelette, sandwich bread and African tea', 8000),
(mid('inganzo'), 'American Breakfast',                  'Ham, fried eggs, brown bread, bacon, cheese, coffee and juice', 10000),
(mid('inganzo'), 'Hearty Inganzo Breakfast',            'Lyonnaise potatoes, sausage, ham, omelette, fruits, juice, coffee and muffin', 12000),
(mid('inganzo'), 'Pumpkin Soup',                        'Creamy pumpkin soup',                            6000),
(mid('inganzo'), 'Vegetable Soup',                      'Garden vegetable soup',                          6000),
(mid('inganzo'), 'Creamy Wild Mushroom Soup',           'Wild mushroom cream soup',                       7000),
(mid('inganzo'), 'Creamy Chicken Soup',                 'Creamy chicken soup',                            8000),
(mid('inganzo'), 'Creamy Fish Soup',                    'Creamy fish soup',                               8000),
(mid('inganzo'), 'Garlic Butter Shrimp',                'Garlic butter shrimp with white wine',          12000),
(mid('inganzo'), 'Avocado Bliss Salad',                 'Fresh avocado salad',                            5000),
(mid('inganzo'), 'Greek Salad',                         'Classic Greek salad',                            6000),
(mid('inganzo'), 'Nicoise Salad',                       'French nicoise salad',                           8000),
(mid('inganzo'), 'Inganzo Chef Garden Salad',           'Signature garden salad',                        10000),
(mid('inganzo'), 'Smoked Atlantic Salmon Salad',        'Premium smoked salmon salad',                   15000),
(mid('inganzo'), 'Succulent Beef Steak',                'Seasoned beef steak with garlic, black pepper and rosemary', 14000),
(mid('inganzo'), 'Slow-Braised Beef Stew',              'Beef braised with onions, tomatoes and peppers', 12000),
(mid('inganzo'), 'Grilled T-Bone Steak',                'T-bone steak with garlic, lemon and rosemary',  16000),
(mid('inganzo'), 'Creamy Beef Stroganoff',              'Beef in rich creamy mushroom sauce',             13000),
(mid('inganzo'), 'Beef Sizzling',                       'Stir-fried beef in savory tomato sauce',        14000),
(mid('inganzo'), 'Sweet Pork Ribs',                     'Sweet-glazed pork ribs',                        13000),
(mid('inganzo'), 'Chicken Cordon Bleu',                 'Stuffed with ham and cheese, breaded',          15000),
(mid('inganzo'), 'Roasted Chicken Leg',                 'Slow roasted chicken leg',                      16000);

-- ─── PAD THAI ────────────────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('pad-thai'), 'Vegetable Spring Roll',              'Crispy vegetable spring rolls',                  3200),
(mid('pad-thai'), 'Chicken Donuts',                     'Thai chicken donut bites',                       7700),
(mid('pad-thai'), 'Papaya Salad',                       'Thai green papaya salad',                        6000),
(mid('pad-thai'), 'Minced Chicken/Beef Salad',          'Thai-style minced meat salad',                   7900),
(mid('pad-thai'), 'Tom Yum Fish Soup',                  'Spicy and sour fish tom yum soup',               8200),
(mid('pad-thai'), 'Tom Yum Beef/Chicken Soup',          'Classic tom yum soup',                           8200),
(mid('pad-thai'), 'Chicken/Beef Coconut Soup',          'Rich coconut milk soup',                         8500),
(mid('pad-thai'), 'Mushroom Soup',                      'Thai mushroom soup',                             5500),
(mid('pad-thai'), 'Basil Chicken/Beef Stir Fry',        'Thai basil stir-fry',                            7500),
(mid('pad-thai'), 'Green Curry Chicken/Beef',           'Thai green curry with rice',                     8500),
(mid('pad-thai'), 'Red Curry Chicken/Beef',             'Thai red curry with rice',                       8500),
(mid('pad-thai'), 'Chicken Phannang Curry',             'Rich Phannang curry',                            8500),
(mid('pad-thai'), 'Vegetable Red/Green Curry',          'Vegetarian Thai curry',                          7000),
(mid('pad-thai'), 'Chili Chicken/Beef',                 'Thai chili stir-fry',                            8200),
(mid('pad-thai'), 'Ginger Chicken',                     'Stir-fried ginger chicken',                      7900),
(mid('pad-thai'), 'Sweet and Sour Chicken',             'Thai sweet and sour chicken',                    8300),
(mid('pad-thai'), 'Chicken Cashew Nuts',                'Chicken with cashew nuts stir-fry',              8300),
(mid('pad-thai'), 'Beef/Chicken Pad Thai',              'Classic pad thai noodles',                       8300),
(mid('pad-thai'), 'Vegetable/Egg Pad Thai',             'Vegetarian pad thai noodles',                    7000),
(mid('pad-thai'), 'Chicken/Beef Fried Rice',            'Thai-style fried rice',                          4900),
(mid('pad-thai'), 'Basil Chicken/Beef Fried Rice',      'Basil fried rice',                               6000),
(mid('pad-thai'), 'Vegetable/Egg Fried Rice',           'Vegetable fried rice',                           3900),
(mid('pad-thai'), 'Steam Rice',                         'Steamed jasmine rice',                           1200),
(mid('pad-thai'), 'Shawarma (Beef/Chicken/Veg)',        'Middle Eastern shawarma wrap',                   6000),
(mid('pad-thai'), 'Herbal Natural Tea',                 'Thai herbal tea',                                3000),
(mid('pad-thai'), 'Fresh Passion Fruit Juice',          'Fresh passion juice',                            3000),
(mid('pad-thai'), 'Lime Mint Juice',                    'Fresh lime and mint juice',                      3000),
(mid('pad-thai'), 'Soda',                               'Coke, Fanta, Sprite',                            1200),
(mid('pad-thai'), 'Beer (SKOL)',                        'Cold Skol beer',                                 1500),
(mid('pad-thai'), 'Water',                              'Mineral water',                                    700);

-- ─── JAPANDA ─────────────────────────────────────────────────
insert into menu_items (merchant_id, name, description, price) values
(mid('japanda'), 'Makunouchi Plate',                    'Teriyaki BBQ chicken, fried chicken, Nile perch, salad, pickled veg, rice and soup', 7500),
(mid('japanda'), 'Tonkotsu Shoyu Ramen',                'Pork broth soy sauce ramen',                     6000),
(mid('japanda'), 'Miso Ramen',                          'Rich miso ramen soup',                           6000),
(mid('japanda'), 'Teriyaki BBQ Chicken Don',            'Teriyaki chicken rice bowl with soup',           5200),
(mid('japanda'), 'Karaage Chicken Don',                 'Fried chicken rice bowl with soup',              5200),
(mid('japanda'), 'Chicken Oyako Don',                   'Egg and chicken rice bowl with soup',            5200),
(mid('japanda'), 'Pork Katsu Don',                      'Pork cutlet rice bowl with soup',                5200),
(mid('japanda'), 'Beef Steak Don',                      'Beef steak rice bowl with soup',                 5200),
(mid('japanda'), 'Sauteed Tofu Don',                    'Tofu rice bowl with soup',                       5200),
(mid('japanda'), 'Ramen and Half Donburi Combo',        'Ramen and half donburi combo',                   8000),
(mid('japanda'), 'Teriyaki Chicken Burger',             'Teriyaki chicken burger with chips',             4500),
(mid('japanda'), 'Fried Chicken Burger',                'Japanese fried chicken burger with chips',       4500),
(mid('japanda'), 'Chicken Leg',                         'Chicken leg with chips and salad',               5000),
(mid('japanda'), 'Karaage Fried Chicken (8pcs)',        'Japanese fried chicken, 8 pieces',               4000),
(mid('japanda'), 'Chicken Nanban (8pcs)',                'Sweet and sour fried chicken, 8 pieces',         5000),
(mid('japanda'), 'Tonkatsu',                            'Pork cutlet with tonkatsu sauce',                4000),
(mid('japanda'), 'Amazu Chicken Wings (5pcs)',          'Japanese sweet and sour chili wings',            4000),
(mid('japanda'), 'Fried Tsukune Balls (7pcs)',          'Minced chicken meatballs',                       3500),
(mid('japanda'), 'Cheese in Katsu',                     'Mozzarella-stuffed chicken breast cutlet',       5000),
(mid('japanda'), 'Crispy Fried Prawns (5pcs)',          'Deep fried prawns with tartar sauce',            7500),
(mid('japanda'), 'Momo Yakitori Thigh',                 'Yakitori chicken thigh skewer, salt or sauce',   2000),
(mid('japanda'), 'Negima Yakitori',                     'Chicken thigh and green onion skewer',           2000),
(mid('japanda'), 'BBQ Prawn Skewer',                    'Grilled prawn skewer with garlic and lemon',     5000),
(mid('japanda'), 'Japanda Salad',                       'Fresh salad with onion dressing',                3500),
(mid('japanda'), 'Japanese Chicken Salad',              'Chicken and cucumber with Japanese dressing',    3000),
(mid('japanda'), 'Juicy Fried Tofu',                    'Deep fried tofu in dashi sauce',                 3000),
(mid('japanda'), 'Vanilla Ice Cream',                   'Homemade vanilla ice cream',                     2500),
(mid('japanda'), 'Soymilk Peanut Ice Cream',            'Vegan homemade peanut ice cream',                3000),
(mid('japanda'), 'Primus (500ml)',                      'Cold Primus beer',                               1500),
(mid('japanda'), 'Mutzig (330ml)',                      'Cold Mutzig beer',                               1500),
(mid('japanda'), 'Heineken (330ml)',                    'Cold Heineken',                                  2000),
(mid('japanda'), 'Sake Glass (140ml)',                  'Japanese sake, Takashimizu',                     5000),
(mid('japanda'), 'Chuhai Cocktail',                     'Fruit-flavored vodka cocktail — lemon, mango or pineapple', 2500),
(mid('japanda'), 'Soda',                                'Cold soda 300ml',                                1000),
(mid('japanda'), 'Water',                               'Mineral water 500ml',                            1000);

-- ─── CLEANUP ─────────────────────────────────────────────────
drop function if exists mid(text);
